// Catálogo do exercício "Busca Rápida" — 7 categorias com imagens 3D
// transparentes (public/exercises/busca/<id>.png). Categorias vizinhas (`NEAR`)
// geram distratores DIFÍCEIS (semanticamente próximos); as demais, fáceis.
// Gerado a partir do acervo de produtos (comida/higiene) + itens 3D.

export interface BuscaItem { id: string; name: string; cat: string; }
export interface BuscaCat { id: string; label: string; }

export const BUSCA_CATS: BuscaCat[] = [
  { id: "hortifruti", label: "Frutas e verduras" },
  { id: "supermercado", label: "Itens de mercado" },
  { id: "higiene", label: "Higiene e limpeza" },
  { id: "roupas", label: "Roupas" },
  { id: "acessorios", label: "Acessórios" },
  { id: "materiais", label: "Materiais escolares" },
  { id: "brinquedos", label: "Brinquedos" },
];

// Categorias semanticamente próximas → distratores difíceis.
export const NEAR: Record<string, string[]> = {
  hortifruti:   ["supermercado"],
  supermercado: ["hortifruti", "higiene"],
  higiene:      ["supermercado", "materiais"],
  roupas:       ["acessorios"],
  acessorios:   ["roupas", "materiais", "brinquedos"],
  materiais:    ["acessorios", "higiene", "brinquedos"],
  brinquedos:   ["materiais", "acessorios"],
};

export const BUSCA_ITEMS: BuscaItem[] = [
  // Frutas e verduras (28)
  { id: "banana", name: "Banana", cat: "hortifruti" },
  { id: "maca", name: "Maçã", cat: "hortifruti" },
  { id: "laranja", name: "Laranja", cat: "hortifruti" },
  { id: "morango", name: "Morango", cat: "hortifruti" },
  { id: "uva", name: "Uva", cat: "hortifruti" },
  { id: "pera", name: "Pera", cat: "hortifruti" },
  { id: "manga", name: "Manga", cat: "hortifruti" },
  { id: "abacaxi", name: "Abacaxi", cat: "hortifruti" },
  { id: "melancia", name: "Melancia", cat: "hortifruti" },
  { id: "limao", name: "Limão", cat: "hortifruti" },
  { id: "tomate", name: "Tomate", cat: "hortifruti" },
  { id: "cebola", name: "Cebola", cat: "hortifruti" },
  { id: "batata", name: "Batata", cat: "hortifruti" },
  { id: "cenoura", name: "Cenoura", cat: "hortifruti" },
  { id: "alface", name: "Alface", cat: "hortifruti" },
  { id: "brocolis", name: "Brócolis", cat: "hortifruti" },
  { id: "abobrinha", name: "Abobrinha", cat: "hortifruti" },
  { id: "pepino", name: "Pepino", cat: "hortifruti" },
  { id: "alho", name: "Alho", cat: "hortifruti" },
  { id: "couve", name: "Couve", cat: "hortifruti" },
  { id: "pimentao", name: "Pimentão", cat: "hortifruti" },
  { id: "mandioca", name: "Mandioca", cat: "hortifruti" },
  { id: "batata-doce", name: "Batata-doce", cat: "hortifruti" },
  { id: "kiwi", name: "Kiwi", cat: "hortifruti" },
  { id: "abacate", name: "Abacate", cat: "hortifruti" },
  { id: "beterraba", name: "Beterraba", cat: "hortifruti" },
  { id: "mamao", name: "Mamão", cat: "hortifruti" },
  { id: "melao", name: "Melão", cat: "hortifruti" },
  // Itens de mercado (85)
  { id: "arroz", name: "Arroz", cat: "supermercado" },
  { id: "feijao", name: "Feijão", cat: "supermercado" },
  { id: "lentilha", name: "Lentilha", cat: "supermercado" },
  { id: "espaguete", name: "Espaguete", cat: "supermercado" },
  { id: "parafuso", name: "Macarrão parafuso", cat: "supermercado" },
  { id: "miojo", name: "Macarrão instantâneo", cat: "supermercado" },
  { id: "farinha-trigo", name: "Farinha de trigo", cat: "supermercado" },
  { id: "fuba", name: "Fubá", cat: "supermercado" },
  { id: "farinha-mandioca", name: "Farinha de mandioca", cat: "supermercado" },
  { id: "amido", name: "Amido de milho", cat: "supermercado" },
  { id: "oleo", name: "Óleo", cat: "supermercado" },
  { id: "azeite", name: "Azeite", cat: "supermercado" },
  { id: "vinagre", name: "Vinagre", cat: "supermercado" },
  { id: "aveia", name: "Aveia", cat: "supermercado" },
  { id: "granola", name: "Granola", cat: "supermercado" },
  { id: "cereal", name: "Cereal", cat: "supermercado" },
  { id: "fermento", name: "Fermento em pó", cat: "supermercado" },
  { id: "batata-frita", name: "Batata frita", cat: "supermercado" },
  { id: "biscoito", name: "Biscoito recheado", cat: "supermercado" },
  { id: "achocolatado", name: "Achocolatado", cat: "supermercado" },
  { id: "acucar", name: "Açúcar", cat: "supermercado" },
  { id: "sal", name: "Sal", cat: "supermercado" },
  { id: "cafe", name: "Café", cat: "supermercado" },
  { id: "pipoca", name: "Pipoca de micro-ondas", cat: "supermercado" },
  { id: "mel", name: "Mel", cat: "supermercado" },
  { id: "geleia-morango", name: "Geleia de morango", cat: "supermercado" },
  { id: "leite-po", name: "Leite em pó", cat: "supermercado" },
  { id: "cream-cracker", name: "Biscoito água e sal", cat: "supermercado" },
  { id: "caldo-carne", name: "Caldo de carne", cat: "supermercado" },
  { id: "pirulito", name: "Pirulito", cat: "supermercado" },
  { id: "amendoim", name: "Amendoim", cat: "supermercado" },
  { id: "batata-chips", name: "Batata chips", cat: "supermercado" },
  { id: "chocolate", name: "Chocolate", cat: "supermercado" },
  { id: "milho", name: "Milho em lata", cat: "supermercado" },
  { id: "ervilha", name: "Ervilha em lata", cat: "supermercado" },
  { id: "atum", name: "Atum", cat: "supermercado" },
  { id: "sardinha", name: "Sardinha", cat: "supermercado" },
  { id: "extrato", name: "Extrato de tomate", cat: "supermercado" },
  { id: "maionese", name: "Maionese", cat: "supermercado" },
  { id: "ketchup", name: "Ketchup", cat: "supermercado" },
  { id: "mostarda", name: "Mostarda", cat: "supermercado" },
  { id: "shoyu", name: "Molho shoyu", cat: "supermercado" },
  { id: "presunto", name: "Presunto", cat: "supermercado" },
  { id: "requeijao", name: "Requeijão", cat: "supermercado" },
  { id: "creme-leite", name: "Creme de leite", cat: "supermercado" },
  { id: "leite-condensado", name: "Leite condensado", cat: "supermercado" },
  { id: "leite", name: "Leite", cat: "supermercado" },
  { id: "queijo", name: "Queijo", cat: "supermercado" },
  { id: "iogurte", name: "Iogurte", cat: "supermercado" },
  { id: "manteiga", name: "Manteiga", cat: "supermercado" },
  { id: "peito-peru", name: "Peito de peru", cat: "supermercado" },
  { id: "margarina", name: "Margarina", cat: "supermercado" },
  { id: "mussarela", name: "Mussarela fatiada", cat: "supermercado" },
  { id: "ovos", name: "Ovos", cat: "supermercado" },
  { id: "peixe", name: "Peixe", cat: "supermercado" },
  { id: "linguica", name: "Linguiça", cat: "supermercado" },
  { id: "salsicha", name: "Salsicha", cat: "supermercado" },
  { id: "hamburguer", name: "Hambúrguer", cat: "supermercado" },
  { id: "frango-assado", name: "Frango assado", cat: "supermercado" },
  { id: "nuggets", name: "Nuggets", cat: "supermercado" },
  { id: "pizza", name: "Pizza congelada", cat: "supermercado" },
  { id: "sorvete", name: "Sorvete", cat: "supermercado" },
  { id: "acai", name: "Açaí", cat: "supermercado" },
  { id: "pao-queijo", name: "Pão de queijo", cat: "supermercado" },
  { id: "ervilha-congelada", name: "Ervilha congelada", cat: "supermercado" },
  { id: "lasanha", name: "Lasanha congelada", cat: "supermercado" },
  { id: "bolo", name: "Bolo", cat: "supermercado" },
  { id: "cookies", name: "Cookies", cat: "supermercado" },
  { id: "pao", name: "Pão", cat: "supermercado" },
  { id: "croissant", name: "Croissant", cat: "supermercado" },
  { id: "donut", name: "Donut", cat: "supermercado" },
  { id: "baguete", name: "Baguete", cat: "supermercado" },
  { id: "rosquinha", name: "Rosquinha", cat: "supermercado" },
  { id: "pao-forma", name: "Pão de forma", cat: "supermercado" },
  { id: "torta-morango", name: "Torta de morango", cat: "supermercado" },
  { id: "energetico", name: "Energético", cat: "supermercado" },
  { id: "agua-coco", name: "Água de coco", cat: "supermercado" },
  { id: "suco-laranja", name: "Suco de laranja", cat: "supermercado" },
  { id: "suco-uva", name: "Suco de uva", cat: "supermercado" },
  { id: "cha", name: "Chá", cat: "supermercado" },
  { id: "agua-mineral", name: "Água mineral", cat: "supermercado" },
  { id: "refrigerante-cola", name: "Refrigerante", cat: "supermercado" },
  { id: "isotonico", name: "Isotônico", cat: "supermercado" },
  { id: "suco-caixinha", name: "Suco de caixinha", cat: "supermercado" },
  { id: "guarana", name: "Guaraná", cat: "supermercado" },
  // Higiene e limpeza (34)
  { id: "detergente", name: "Detergente", cat: "higiene" },
  { id: "detergente-limao", name: "Detergente limão", cat: "higiene" },
  { id: "limpador-multiuso", name: "Limpador multiuso", cat: "higiene" },
  { id: "limpa-vidros", name: "Limpa-vidros", cat: "higiene" },
  { id: "desengordurante", name: "Desengordurante", cat: "higiene" },
  { id: "limpador-sanitario", name: "Limpador sanitário", cat: "higiene" },
  { id: "desinfetante", name: "Desinfetante", cat: "higiene" },
  { id: "agua-sanitaria", name: "Água sanitária", cat: "higiene" },
  { id: "alcool", name: "Álcool", cat: "higiene" },
  { id: "alcool-gel", name: "Álcool em gel", cat: "higiene" },
  { id: "sabao-liquido", name: "Sabão líquido", cat: "higiene" },
  { id: "esponja", name: "Esponja", cat: "higiene" },
  { id: "saco-lixo", name: "Saco de lixo", cat: "higiene" },
  { id: "pano", name: "Pano de limpeza", cat: "higiene" },
  { id: "papel-toalha", name: "Papel toalha", cat: "higiene" },
  { id: "sabao-po", name: "Sabão em pó", cat: "higiene" },
  { id: "detergente-po", name: "Detergente em pó", cat: "higiene" },
  { id: "sabao-barra", name: "Sabão em barra", cat: "higiene" },
  { id: "amaciante", name: "Amaciante", cat: "higiene" },
  { id: "sabonete", name: "Sabonete", cat: "higiene" },
  { id: "sabonete-laranja", name: "Sabonete laranja", cat: "higiene" },
  { id: "sabonete-liquido", name: "Sabonete líquido", cat: "higiene" },
  { id: "escova", name: "Escova de dente", cat: "higiene" },
  { id: "creme-dental", name: "Creme dental", cat: "higiene" },
  { id: "fio-dental", name: "Fio dental", cat: "higiene" },
  { id: "enxaguante", name: "Enxaguante bucal", cat: "higiene" },
  { id: "shampoo", name: "Shampoo", cat: "higiene" },
  { id: "condicionador", name: "Condicionador", cat: "higiene" },
  { id: "desodorante", name: "Desodorante", cat: "higiene" },
  { id: "protetor-solar", name: "Protetor solar", cat: "higiene" },
  { id: "creme-maos", name: "Creme para as mãos", cat: "higiene" },
  { id: "lencos-umedecidos", name: "Lenços umedecidos", cat: "higiene" },
  { id: "cotonete", name: "Cotonete", cat: "higiene" },
  { id: "fralda", name: "Fralda", cat: "higiene" },
  // Roupas (36)
  { id: "camiseta", name: "Camiseta", cat: "roupas" },
  { id: "camisa", name: "Camisa", cat: "roupas" },
  { id: "bermuda-jeans", name: "Bermuda jeans", cat: "roupas" },
  { id: "vestido", name: "Vestido", cat: "roupas" },
  { id: "jaqueta-puffer", name: "Jaqueta puffer", cat: "roupas" },
  { id: "blusa", name: "Blusa", cat: "roupas" },
  { id: "saia", name: "Saia", cat: "roupas" },
  { id: "shorts", name: "Shorts", cat: "roupas" },
  { id: "pijama", name: "Pijama", cat: "roupas" },
  { id: "moletom", name: "Moletom", cat: "roupas" },
  { id: "jaqueta", name: "Jaqueta", cat: "roupas" },
  { id: "regata", name: "Regata", cat: "roupas" },
  { id: "camisa-polo", name: "Camisa polo", cat: "roupas" },
  { id: "bermuda", name: "Bermuda", cat: "roupas" },
  { id: "jardineira", name: "Jardineira", cat: "roupas" },
  { id: "sueter", name: "Suéter", cat: "roupas" },
  { id: "legging", name: "Legging", cat: "roupas" },
  { id: "avental", name: "Avental", cat: "roupas" },
  { id: "blazer", name: "Blazer", cat: "roupas" },
  { id: "colete", name: "Colete", cat: "roupas" },
  { id: "body-bebe", name: "Body de bebê", cat: "roupas" },
  { id: "casaco", name: "Casaco", cat: "roupas" },
  { id: "biquini", name: "Biquíni", cat: "roupas" },
  { id: "maio", name: "Maiô", cat: "roupas" },
  { id: "macaquinho", name: "Macaquinho", cat: "roupas" },
  { id: "canga", name: "Canga", cat: "roupas" },
  { id: "vestido-longo", name: "Vestido longo", cat: "roupas" },
  { id: "blusa-uv", name: "Blusa UV", cat: "roupas" },
  { id: "robe", name: "Robe", cat: "roupas" },
  { id: "shorts-praia", name: "Shorts de praia", cat: "roupas" },
  { id: "parka", name: "Parka", cat: "roupas" },
  { id: "calca", name: "Calça", cat: "roupas" },
  { id: "saia-plissada", name: "Saia plissada", cat: "roupas" },
  { id: "cardiga", name: "Cardigã", cat: "roupas" },
  { id: "blusa-listrada", name: "Blusa listrada", cat: "roupas" },
  { id: "calca-bege", name: "Calça bege", cat: "roupas" },
  // Acessórios (44)
  { id: "touca", name: "Touca", cat: "acessorios" },
  { id: "cachecol", name: "Cachecol", cat: "acessorios" },
  { id: "bota", name: "Bota", cat: "acessorios" },
  { id: "toalha-praia", name: "Toalha de praia", cat: "acessorios" },
  { id: "bone", name: "Boné", cat: "acessorios" },
  { id: "oculos", name: "Óculos", cat: "acessorios" },
  { id: "fone", name: "Fone de ouvido", cat: "acessorios" },
  { id: "cinto", name: "Cinto", cat: "acessorios" },
  { id: "guarda-chuva", name: "Guarda-chuva", cat: "acessorios" },
  { id: "bolsa", name: "Bolsa", cat: "acessorios" },
  { id: "tiara", name: "Tiara", cat: "acessorios" },
  { id: "relogio", name: "Relógio", cat: "acessorios" },
  { id: "brinco", name: "Brinco", cat: "acessorios" },
  { id: "chapeu", name: "Chapéu", cat: "acessorios" },
  { id: "gravata", name: "Gravata", cat: "acessorios" },
  { id: "gravata-borboleta", name: "Gravata borboleta", cat: "acessorios" },
  { id: "pochete", name: "Pochete", cat: "acessorios" },
  { id: "lenco", name: "Lenço", cat: "acessorios" },
  { id: "presilha", name: "Presilha", cat: "acessorios" },
  { id: "pulseira", name: "Pulseira", cat: "acessorios" },
  { id: "luva", name: "Luva", cat: "acessorios" },
  { id: "carteira", name: "Carteira", cat: "acessorios" },
  { id: "faixa-cabelo", name: "Faixa de cabelo", cat: "acessorios" },
  { id: "anel", name: "Anel", cat: "acessorios" },
  { id: "chaveiro", name: "Chaveiro", cat: "acessorios" },
  { id: "necessaire", name: "Nécessaire", cat: "acessorios" },
  { id: "porta-moedas", name: "Porta-moedas", cat: "acessorios" },
  { id: "xuxinha", name: "Xuxinha", cat: "acessorios" },
  { id: "brinco-argola", name: "Brinco de argola", cat: "acessorios" },
  { id: "boina", name: "Boina", cat: "acessorios" },
  { id: "bandana", name: "Bandana", cat: "acessorios" },
  { id: "relogio-bolso", name: "Relógio de bolso", cat: "acessorios" },
  { id: "presilha-flor", name: "Presilha de flor", cat: "acessorios" },
  { id: "colar", name: "Colar", cat: "acessorios" },
  { id: "mascara-dormir", name: "Máscara de dormir", cat: "acessorios" },
  { id: "echarpe", name: "Echarpe", cat: "acessorios" },
  { id: "orelheira", name: "Orelheira", cat: "acessorios" },
  { id: "suspensorio", name: "Suspensório", cat: "acessorios" },
  { id: "oculos-aviador", name: "Óculos aviador", cat: "acessorios" },
  { id: "bolsa-tote", name: "Bolsa tote", cat: "acessorios" },
  { id: "chinelo", name: "Chinelo", cat: "acessorios" },
  { id: "sapato", name: "Sapato", cat: "acessorios" },
  { id: "sandalia", name: "Sandália", cat: "acessorios" },
  { id: "smartwatch", name: "Smartwatch", cat: "acessorios" },
  // Materiais escolares (11)
  { id: "mochila", name: "Mochila", cat: "materiais" },
  { id: "caneta", name: "Caneta", cat: "materiais" },
  { id: "lapis", name: "Lápis", cat: "materiais" },
  { id: "borracha", name: "Borracha", cat: "materiais" },
  { id: "apontador", name: "Apontador", cat: "materiais" },
  { id: "livro", name: "Livro", cat: "materiais" },
  { id: "bloco-notas", name: "Bloco de notas", cat: "materiais" },
  { id: "grampeador", name: "Grampeador", cat: "materiais" },
  { id: "clips", name: "Clipes", cat: "materiais" },
  { id: "calculadora", name: "Calculadora", cat: "materiais" },
  { id: "fita-adesiva", name: "Fita adesiva", cat: "materiais" },
  // Brinquedos (13)
  { id: "ursinho", name: "Ursinho de pelúcia", cat: "brinquedos" },
  { id: "blocos", name: "Blocos de montar", cat: "brinquedos" },
  { id: "carrinho", name: "Carrinho", cat: "brinquedos" },
  { id: "boneca", name: "Boneca", cat: "brinquedos" },
  { id: "bola", name: "Bola", cat: "brinquedos" },
  { id: "helicoptero", name: "Helicóptero", cat: "brinquedos" },
  { id: "dinossauro", name: "Dinossauro", cat: "brinquedos" },
  { id: "caminhao", name: "Caminhão", cat: "brinquedos" },
  { id: "argolas", name: "Argolas de empilhar", cat: "brinquedos" },
  { id: "dardos", name: "Jogo de dardos", cat: "brinquedos" },
  { id: "xilofone", name: "Xilofone", cat: "brinquedos" },
  { id: "aviao", name: "Avião", cat: "brinquedos" },
  { id: "boliche", name: "Boliche", cat: "brinquedos" },
];

export function itemsByCat(catId: string): BuscaItem[] {
  return BUSCA_ITEMS.filter(i => i.cat === catId);
}
export function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; }
  return a;
}
